# ============================================================================
# setup_azure.ps1
# ============================================================================
<#
.SYNOPSIS
    Setup Azure resources for Agentic ML Builder

.DESCRIPTION
    Creates necessary Azure resources including:
    - Resource Group
    - Azure ML Workspace
    - Storage Account
    - Container Registry
    - Key Vault
    - Application Insights

.EXAMPLE
    .\setup_azure.ps1
#>

param(
    [string]$ResourceGroup = "ml-builder-rg",
    [string]$Location = "eastus",
    [string]$WorkspaceName = "ml-builder-workspace",
    [string]$StorageAccountName = "mlbuilderstorage$(Get-Random -Maximum 9999)",
    [string]$KeyVaultName = "ml-builder-kv-$(Get-Random -Maximum 9999)",
    [string]$AppInsightsName = "ml-builder-insights"
)

Write-Host "======================================" -ForegroundColor Cyan
Write-Host "Azure ML Builder Setup" -ForegroundColor Cyan
Write-Host "======================================" -ForegroundColor Cyan
Write-Host ""

# Check if Azure CLI is installed
Write-Host "Checking Azure CLI installation..." -ForegroundColor Yellow
try {
    $azVersion = az version | ConvertFrom-Json
    Write-Host "✓ Azure CLI version: $($azVersion.'azure-cli')" -ForegroundColor Green
}
catch {
    Write-Host "✗ Azure CLI not found. Please install from: https://aka.ms/installazurecliwindows" -ForegroundColor Red
    exit 1
}

# Login to Azure
Write-Host "`nLogging in to Azure..." -ForegroundColor Yellow
az login
if ($LASTEXITCODE -ne 0) {
    Write-Host "✗ Azure login failed" -ForegroundColor Red
    exit 1
}
Write-Host "✓ Logged in successfully" -ForegroundColor Green

# Set subscription
Write-Host "`nSetting subscription..." -ForegroundColor Yellow
$subscriptionId = $env:AZURE_SUBSCRIPTION_ID
if ($subscriptionId) {
    az account set --subscription $subscriptionId
    Write-Host "✓ Subscription set to: $subscriptionId" -ForegroundColor Green
}
else {
    Write-Host "! Using default subscription" -ForegroundColor Yellow
}

# Create Resource Group
Write-Host "`nCreating Resource Group: $ResourceGroup" -ForegroundColor Yellow
az group create --name $ResourceGroup --location $Location
if ($LASTEXITCODE -eq 0) {
    Write-Host "✓ Resource Group created" -ForegroundColor Green
}
else {
    Write-Host "✗ Failed to create Resource Group" -ForegroundColor Red
    exit 1
}

# Create Storage Account
Write-Host "`nCreating Storage Account: $StorageAccountName" -ForegroundColor Yellow
az storage account create `
    --name $StorageAccountName `
    --resource-group $ResourceGroup `
    --location $Location `
    --sku Standard_LRS `
    --kind StorageV2
if ($LASTEXITCODE -eq 0) {
    Write-Host "✓ Storage Account created" -ForegroundColor Green
}
else {
    Write-Host "✗ Failed to create Storage Account" -ForegroundColor Red
}

# Create Key Vault
Write-Host "`nCreating Key Vault: $KeyVaultName" -ForegroundColor Yellow
az keyvault create `
    --name $KeyVaultName `
    --resource-group $ResourceGroup `
    --location $Location
if ($LASTEXITCODE -eq 0) {
    Write-Host "✓ Key Vault created" -ForegroundColor Green
}
else {
    Write-Host "✗ Failed to create Key Vault" -ForegroundColor Red
}

# Create Application Insights
Write-Host "`nCreating Application Insights: $AppInsightsName" -ForegroundColor Yellow
az monitor app-insights component create `
    --app $AppInsightsName `
    --location $Location `
    --resource-group $ResourceGroup `
    --kind web
if ($LASTEXITCODE -eq 0) {
    Write-Host "✓ Application Insights created" -ForegroundColor Green
}
else {
    Write-Host "✗ Failed to create Application Insights" -ForegroundColor Red
}

# Create Azure ML Workspace
Write-Host "`nCreating Azure ML Workspace: $WorkspaceName" -ForegroundColor Yellow
az ml workspace create `
    --name $WorkspaceName `
    --resource-group $ResourceGroup `
    --location $Location
if ($LASTEXITCODE -eq 0) {
    Write-Host "✓ Azure ML Workspace created" -ForegroundColor Green
}
else {
    Write-Host "✗ Failed to create Azure ML Workspace" -ForegroundColor Red
}

# Create compute cluster
Write-Host "`nCreating compute cluster: gpu-cluster" -ForegroundColor Yellow
az ml compute create `
    --name gpu-cluster `
    --resource-group $ResourceGroup `
    --workspace-name $WorkspaceName `
    --type AmlCompute `
    --size Standard_NC6s_v3 `
    --min-instances 0 `
    --max-instances 4
if ($LASTEXITCODE -eq 0) {
    Write-Host "✓ Compute cluster created" -ForegroundColor Green
}
else {
    Write-Host "! Compute cluster creation failed (may need manual setup)" -ForegroundColor Yellow
}

# Save configuration
Write-Host "`nSaving configuration to .env file..." -ForegroundColor Yellow
$envContent = @"
# Azure Configuration - Auto-generated by setup_azure.ps1
AZURE_SUBSCRIPTION_ID=$subscriptionId
AZURE_RESOURCE_GROUP=$ResourceGroup
AZURE_LOCATION=$Location
AZURE_AI_PROJECT_NAME=$WorkspaceName
AZURE_STORAGE_ACCOUNT=$StorageAccountName
AZURE_KEY_VAULT=$KeyVaultName
AZURE_APP_INSIGHTS=$AppInsightsName
"@

Add-Content -Path ".env" -Value "`n$envContent"
Write-Host "✓ Configuration saved to .env" -ForegroundColor Green

# Summary
Write-Host "`n======================================" -ForegroundColor Cyan
Write-Host "Setup Complete!" -ForegroundColor Cyan
Write-Host "======================================" -ForegroundColor Cyan
Write-Host "`nResources created:" -ForegroundColor Green
Write-Host "  • Resource Group: $ResourceGroup"
Write-Host "  • ML Workspace: $WorkspaceName"
Write-Host "  • Storage Account: $StorageAccountName"
Write-Host "  • Key Vault: $KeyVaultName"
Write-Host "  • App Insights: $AppInsightsName"
Write-Host "  • Compute Cluster: gpu-cluster"
Write-Host "`nNext steps:" -ForegroundColor Yellow
Write-Host "  1. Update .env file with your OpenAI API key"
Write-Host "  2. Run: python src/main.py --input input/scene_dataset.json --output output"
Write-Host ""


# ============================================================================
# deploy_foundry.ps1
# ============================================================================
<#
.SYNOPSIS
    Deploy ML project to Azure AI Foundry

.DESCRIPTION
    Deploys generated ML project to Azure AI Foundry for training and deployment

.EXAMPLE
    .\deploy_foundry.ps1 -ProjectPath "output/scene_classifier"
#>

param(
    [Parameter(Mandatory=$true)]
    [string]$ProjectPath,
    
    [string]$ResourceGroup = $env:AZURE_RESOURCE_GROUP,
    [string]$WorkspaceName = $env:AZURE_AI_PROJECT_NAME,
    [string]$ExperimentName = "ml-experiment",
    [string]$ComputeTarget = "gpu-cluster"
)

Write-Host "======================================" -ForegroundColor Cyan
Write-Host "Azure AI Foundry Deployment" -ForegroundColor Cyan
Write-Host "======================================" -ForegroundColor Cyan
Write-Host ""

# Validate inputs
if (-not (Test-Path $ProjectPath)) {
    Write-Host "✗ Project path not found: $ProjectPath" -ForegroundColor Red
    exit 1
}

if (-not $ResourceGroup -or -not $WorkspaceName) {
    Write-Host "✗ Azure configuration not found. Run setup_azure.ps1 first." -ForegroundColor Red
    exit 1
}

Write-Host "Project: $ProjectPath" -ForegroundColor Yellow
Write-Host "Workspace: $WorkspaceName" -ForegroundColor Yellow
Write-Host "Resource Group: $ResourceGroup" -ForegroundColor Yellow
Write-Host ""

# Login check
Write-Host "Checking Azure login..." -ForegroundColor Yellow
az account show > $null 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "! Not logged in. Logging in..." -ForegroundColor Yellow
    az login
}
Write-Host "✓ Logged in" -ForegroundColor Green

# Create environment file
Write-Host "`nCreating conda environment file..." -ForegroundColor Yellow
$condaEnv = @"
name: ml-environment
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - pip:
    - torch==2.5.1
    - torchvision==0.20.1
    - scikit-learn==1.5.2
    - pandas==2.2.3
    - numpy==2.1.3
    - matplotlib==3.9.2
    - mlflow==2.18.0
    - azureml-mlflow==1.59.0
"@

$condaEnv | Out-File -FilePath "$ProjectPath/conda_env.yml" -Encoding utf8
Write-Host "✓ Environment file created" -ForegroundColor Green

# Create Azure ML job configuration
Write-Host "`nCreating job configuration..." -ForegroundColor Yellow
$jobConfig = @"
`$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json

type: command
experiment_name: $ExperimentName
display_name: training-job-$(Get-Date -Format 'yyyyMMdd-HHmmss')
description: ML training job deployed by Agentic ML Builder

compute: azureml:$ComputeTarget

environment:
  image: mcr.microsoft.com/azureml/openmpi4.1.0-cuda11.1-cudnn8-ubuntu20.04
  conda_file: conda_env.yml

code: .

command: >-
  python train.py
  --epochs 10
  --batch-size 32
  --learning-rate 0.001

outputs:
  model_output:
    type: uri_folder
    mode: rw_mount

resources:
  instance_count: 1
"@

$jobConfig | Out-File -FilePath "$ProjectPath/job.yml" -Encoding utf8
Write-Host "✓ Job configuration created" -ForegroundColor Green

# Submit job
Write-Host "`nSubmitting training job..." -ForegroundColor Yellow
Push-Location $ProjectPath
try {
    az ml job create `
        --file job.yml `
        --resource-group $ResourceGroup `
        --workspace-name $WorkspaceName `
        --stream
    
    if ($LASTEXITCODE -eq 0) {
        Write-Host "✓ Job submitted successfully" -ForegroundColor Green
    }
    else {
        Write-Host "✗ Job submission failed" -ForegroundColor Red
    }
}
finally {
    Pop-Location
}

# Show job status
Write-Host "`nTo monitor job:" -ForegroundColor Yellow
Write-Host "  az ml job list --resource-group $ResourceGroup --workspace-name $WorkspaceName"
Write-Host "`nTo view in portal:" -ForegroundColor Yellow
Write-Host "  https://ml.azure.com"
Write-Host ""


# ============================================================================
# run_local.ps1
# ============================================================================
<#
.SYNOPSIS
    Run ML Builder locally

.DESCRIPTION
    Runs the Agentic ML Builder on a local Windows machine

.EXAMPLE
    .\run_local.ps1 -DatasetType "scene"
#>

param(
    [Parameter(Mandatory=$true)]
    [ValidateSet("scene", "lyrics", "birds", "custom")]
    [string]$DatasetType,
    
    [string]$CustomInput,
    [string]$OutputDir = "output",
    [switch]$Validate
)

Write-Host "======================================" -ForegroundColor Cyan
Write-Host "Agentic ML Builder - Local Execution" -ForegroundColor Cyan
Write-Host "======================================" -ForegroundColor Cyan
Write-Host ""

# Check virtual environment
if (-not $env:VIRTUAL_ENV) {
    Write-Host "! Virtual environment not activated" -ForegroundColor Yellow
    Write-Host "  Activating..." -ForegroundColor Yellow
    
    if (Test-Path "venv\Scripts\Activate.ps1") {
        & ".\venv\Scripts\Activate.ps1"
        Write-Host "✓ Virtual environment activated" -ForegroundColor Green
    }
    else {
        Write-Host "✗ Virtual environment not found. Run: python -m venv venv" -ForegroundColor Red
        exit 1
    }
}

# Check .env file
if (-not (Test-Path ".env")) {
    Write-Host "✗ .env file not found. Please create it with your API keys." -ForegroundColor Red
    exit 1
}

# Create input directory
if (-not (Test-Path "input")) {
    New-Item -ItemType Directory -Path "input" | Out-Null
}

# Select or create input file
$inputFile = ""
switch ($DatasetType) {
    "scene" {
        $inputFile = "input/scene_dataset.json"
        $spec = @{
            project_name = "scene_classifier"
            purpose = "Multi-label scene classification"
            data_type = "image"
            dataset_url = "https://www.openml.org/api/v1/json/data/40595"
            ml_task = "classification"
            target_environment = "local"
            models = @("resnet", "efficientnet")
        } | ConvertTo-Json
        $spec | Out-File -FilePath $inputFile -Encoding utf8
    }
    "lyrics" {
        $inputFile = "input/lyrics_dataset.json"
        $spec = @{
            project_name = "lyrics_sentiment"
            purpose = "Lyrics sentiment analysis"
            data_type = "text"
            dataset_url = "https://www.openml.org/api/v1/json/data/43597"
            ml_task = "regression"
            target_environment = "local"
            models = @("bert", "lstm")
        } | ConvertTo-Json
        $spec | Out-File -FilePath $inputFile -Encoding utf8
    }
    "birds" {
        $inputFile = "input/birds_dataset.json"
        $spec = @{
            project_name = "bird_classifier"
            purpose = "Bird species classification"
            data_type = "audio"
            dataset_url = "https://www.openml.org/api/v1/json/data/40588"
            ml_task = "classification"
            target_environment = "local"
            models = @("cnn", "transformer")
        } | ConvertTo-Json
        $spec | Out-File -FilePath $inputFile -Encoding utf8
    }
    "custom" {
        if (-not $CustomInput) {
            Write-Host "✗ Custom input file path required" -ForegroundColor Red
            exit 1
        }
        $inputFile = $CustomInput
    }
}

Write-Host "Input: $inputFile" -ForegroundColor Yellow
Write-Host "Output: $OutputDir" -ForegroundColor Yellow
Write-Host ""

# Run ML Builder
Write-Host "Starting ML Builder..." -ForegroundColor Yellow
$validateArg = if ($Validate) { "--validate" } else { "" }

python src/main.py --input $inputFile --output $OutputDir $validateArg

if ($LASTEXITCODE -eq 0) {
    Write-Host "`n✓ ML Builder completed successfully!" -ForegroundColor Green
    Write-Host "`nGenerated project available in: $OutputDir" -ForegroundColor Green
}
else {
    Write-Host "`n✗ ML Builder failed" -ForegroundColor Red
    exit 1
}

Write-Host ""
