# ============================================================================
# setup_azure.ps1
# ============================================================================
<#
.SYNOPSIS
    Setup Azure resources for Agentic ML Builder

.DESCRIPTION
    Creates necessary Azure resources including:
    - Resource Group
    - Azure ML Workspace
    - Storage Account
    - Container Registry
    - Key Vault
    - Application Insights

.EXAMPLE
    .\setup_azure.ps1
#>

param(
    [string]$ResourceGroup = "ml-builder-rg",
    [string]$Location = "eastus",
    [string]$WorkspaceName = "ml-builder-workspace",
    [string]$StorageAccountName = "mlbuilderstorage$(Get-Random -Maximum 9999)",
    [string]$KeyVaultName = "ml-builder-kv-$(Get-Random -Maximum 9999)",
    [string]$AppInsightsName = "ml-builder-insights"
)

Write-Host "======================================" -ForegroundColor Cyan
Write-Host "Azure ML Builder Setup" -ForegroundColor Cyan
Write-Host "======================================" -ForegroundColor Cyan
Write-Host ""

# Check if Azure CLI is installed
Write-Host "Checking Azure CLI installation..." -ForegroundColor Yellow
try {
    $azVersion = az version | ConvertFrom-Json
    Write-Host "✓ Azure CLI version: $($azVersion.'azure-cli')" -ForegroundColor Green
}
catch {
    Write-Host "✗ Azure CLI not found. Please install from: https://aka.ms/installazurecliwindows" -ForegroundColor Red
    exit 1
}

# Login to Azure
Write-Host "`nLogging in to Azure..." -ForegroundColor Yellow
az login
if ($LASTEXITCODE -ne 0) {
    Write-Host "✗ Azure login failed" -ForegroundColor Red
    exit 1
}
Write-Host "✓ Logged in successfully" -ForegroundColor Green

# Set subscription
Write-Host "`nSetting subscription..." -ForegroundColor Yellow
$subscriptionId = $env:AZURE_SUBSCRIPTION_ID
if ($subscriptionId) {
    az account set --subscription $subscriptionId
    Write-Host "✓ Subscription set to: $subscriptionId" -ForegroundColor Green
}
else {
    Write-Host "! Using default subscription" -ForegroundColor Yellow
}

# Create Resource Group
Write-Host "`nCreating Resource Group: $ResourceGroup" -ForegroundColor Yellow
az group create --name $ResourceGroup --location $Location
if ($LASTEXITCODE -eq 0) {
    Write-Host "✓ Resource Group created" -ForegroundColor Green
}
else {
    Write-Host "✗ Failed to create Resource Group" -ForegroundColor Red
    exit 1
}

# Create Storage Account
Write-Host "`nCreating Storage Account: $StorageAccountName" -ForegroundColor Yellow
az storage account create `
    --name $StorageAccountName `
    --resource-group $ResourceGroup `
    --location $Location `
    --sku Standard_LRS `
    --kind StorageV2
if ($LASTEXITCODE -eq 0) {
    Write-Host "✓ Storage Account created" -ForegroundColor Green
}
else {
    Write-Host "✗ Failed to create Storage Account" -ForegroundColor Red
}

# Create Key Vault
Write-Host "`nCreating Key Vault: $KeyVaultName" -ForegroundColor Yellow
az keyvault create `
    --name $KeyVaultName `
    --resource-group $ResourceGroup `
    --location $Location
if ($LASTEXITCODE -eq 0) {
    Write-Host "✓ Key Vault created" -ForegroundColor Green
}
else {
    Write-Host "✗ Failed to create Key Vault" -ForegroundColor Red
}

# Create Application Insights
Write-Host "`nCreating Application Insights: $AppInsightsName" -ForegroundColor Yellow
az monitor app-insights component create `
    --app $AppInsightsName `
    --location $Location `
    --resource-group $ResourceGroup `
    --kind web
if ($LASTEXITCODE -eq 0) {
    Write-Host "✓ Application Insights created" -ForegroundColor Green
}
else {
    Write-Host "✗ Failed to create Application Insights" -ForegroundColor Red
}

# Create Azure ML Workspace
Write-Host "`nCreating Azure ML Workspace: $WorkspaceName" -ForegroundColor Yellow
az ml workspace create `
    --name $WorkspaceName `
    --resource-group $ResourceGroup `
    --location $Location
if ($LASTEXITCODE -eq 0) {
    Write-Host "✓ Azure ML Workspace created" -ForegroundColor Green
}
else {
    Write-Host "✗ Failed to create Azure ML Workspace" -ForegroundColor Red
}

# Create compute cluster
Write-Host "`nCreating compute cluster: gpu-cluster" -ForegroundColor Yellow
az ml compute create `
    --name gpu-cluster `
    --resource-group $ResourceGroup `
    --workspace-name $WorkspaceName `
    --type AmlCompute `
    --size Standard_NC6s_v3 `
    --min-instances 0 `
    --max-instances 4
if ($LASTEXITCODE -eq 0) {
    Write-Host "✓ Compute cluster created" -ForegroundColor Green
}
else {
    Write-Host "! Compute cluster creation failed (may need manual setup)" -ForegroundColor Yellow
}

# Save configuration
Write-Host "`nSaving configuration to .env file..." -ForegroundColor Yellow
$envContent = @"
# Azure Configuration - Auto-generated by setup_azure.ps1
AZURE_SUBSCRIPTION_ID=$subscriptionId
AZURE_RESOURCE_GROUP=$ResourceGroup
AZURE_LOCATION=$Location
AZURE_AI_PROJECT_NAME=$WorkspaceName
AZURE_STORAGE_ACCOUNT=$StorageAccountName
AZURE_KEY_VAULT=$KeyVaultName
AZURE_APP_INSIGHTS=$AppInsightsName
"@

Add-Content -Path ".env" -Value "`n$envContent"
Write-Host "✓ Configuration saved to .env" -ForegroundColor Green

# Summary
Write-Host "`n======================================" -ForegroundColor Cyan
Write-Host "Setup Complete!" -ForegroundColor Cyan
Write-Host "======================================" -ForegroundColor Cyan
Write-Host "`nResources created:" -ForegroundColor Green
Write-Host "  • Resource Group: $ResourceGroup"
Write-Host "  • ML Workspace: $WorkspaceName"
Write-Host "  • Storage Account: $StorageAccountName"
Write-Host "  • Key Vault: $KeyVaultName"
Write-Host "  • App Insights: $AppInsightsName"
Write-Host "  • Compute Cluster: gpu-cluster"
Write-Host "`nNext steps:" -ForegroundColor Yellow
Write-Host "  1. Update .env file with your OpenAI API key"
Write-Host "  2. Run: python src/main.py --input input/scene_dataset.json --output output"
Write-Host ""

