# ============================================================================
# azure_utils.py
# ============================================================================
"""
Azure utilities for interacting with Azure Machine Learning and Blob Storage.

Module responsibilities
- Initialize Azure ML and Storage clients using environment credentials.
- Submit training jobs and register models with Azure ML.
- Upload and download artifacts to/from Azure Blob Storage.

Environment variables
- `AZURE_SUBSCRIPTION_ID` - Azure subscription id used by MLClient
- `AZURE_RESOURCE_GROUP` - Resource group containing the workspace
- `AZURE_AI_PROJECT_NAME` - Azure ML workspace name
- `AZURE_STORAGE_CONNECTION_STRING` - Connection string for Blob Storage

Usage example
```
from utils.azure_utils import AzureClient, AzureStorageClient

ml = AzureClient()
storage = AzureStorageClient()
```
"""
import logging
import os
from azure.identity import DefaultAzureCredential
from azure.ai.ml import MLClient
from azure.storage.blob import BlobServiceClient
from pathlib import Path

logger = logging.getLogger(__name__)

class AzureClient:
    """Client wrapper for Azure Machine Learning operations.

    Responsibilities:
    - Initialize `azure.ai.ml.MLClient` using `DefaultAzureCredential` and
      the environment variables listed in the module header.
    - Submit training jobs via `submit_training_job`.
    - Register models via `register_model`.

    If required environment variables are missing the underlying ML client
    will not be initialized and calls that require it will raise
    `RuntimeError`.
    """

    def __init__(self):
        self.credential = DefaultAzureCredential()
        self.subscription_id = os.getenv("AZURE_SUBSCRIPTION_ID")
        self.resource_group = os.getenv("AZURE_RESOURCE_GROUP")
        self.workspace_name = os.getenv("AZURE_AI_PROJECT_NAME")
        
        if all([self.subscription_id, self.resource_group, self.workspace_name]):
            self.ml_client = MLClient(
                credential=self.credential,
                subscription_id=self.subscription_id,
                resource_group_name=self.resource_group,
                workspace_name=self.workspace_name
            )
            logger.info("Azure ML client initialized")
        else:
            self.ml_client = None
            logger.warning("Azure ML client not initialized - missing configuration")
    
    def submit_training_job(self, job_config: dict):
        """Submit training job to Azure ML"""
        if not self.ml_client:
            raise RuntimeError("Azure ML client not initialized")
        
        from azure.ai.ml import command
        
        job = command(
            code=job_config.get('code_path', './'),
            command=job_config.get('command'),
            environment=job_config.get('environment'),
            compute=job_config.get('compute_target', 'gpu-cluster'),
            display_name=job_config.get('display_name'),
            experiment_name=job_config.get('experiment_name')
        )
        
        submitted_job = self.ml_client.jobs.create_or_update(job)
        logger.info(f"Job submitted: {submitted_job.name}")
        return submitted_job
    
    def register_model(self, model_path: Path, model_name: str):
        """Register model in Azure ML"""
        if not self.ml_client:
            raise RuntimeError("Azure ML client not initialized")
        
        from azure.ai.ml.entities import Model
        from azure.ai.ml.constants import AssetTypes
        
        model = Model(
            path=str(model_path),
            type=AssetTypes.CUSTOM_MODEL,
            name=model_name,
            description="Model generated by Agentic ML Builder"
        )
        
        registered_model = self.ml_client.models.create_or_update(model)
        logger.info(f"Model registered: {registered_model.name}")
        return registered_model


class AzureStorageClient:
    """Wrapper for common Azure Blob Storage operations.

    Responsibilities:
    - Initialize `BlobServiceClient` from `AZURE_STORAGE_CONNECTION_STRING`.
    - Upload local files to a blob container using `upload_file`.
    - Download blobs to a local path using `download_file`.

    If `AZURE_STORAGE_CONNECTION_STRING` is not set the storage client will
    not be initialized and calls will raise `RuntimeError`.
    """
    
    def __init__(self):
        connection_string = os.getenv("AZURE_STORAGE_CONNECTION_STRING")
        if connection_string:
            self.blob_service_client = BlobServiceClient.from_connection_string(
                connection_string
            )
            logger.info("Azure Storage client initialized")
        else:
            self.blob_service_client = None
            logger.warning("Azure Storage client not initialized")
    
    def upload_file(self, file_path: Path, container_name: str, blob_name: str):
        """Upload file to blob storage"""
        if not self.blob_service_client:
            raise RuntimeError("Azure Storage client not initialized")
        
        blob_client = self.blob_service_client.get_blob_client(
            container=container_name,
            blob=blob_name
        )
        
        with open(file_path, "rb") as data:
            blob_client.upload_blob(data, overwrite=True)
        
        logger.info(f"Uploaded {file_path} to {container_name}/{blob_name}")
    
    def download_file(self, container_name: str, blob_name: str, download_path: Path):
        """Download file from blob storage"""
        if not self.blob_service_client:
            raise RuntimeError("Azure Storage client not initialized")
        
        blob_client = self.blob_service_client.get_blob_client(
            container=container_name,
            blob=blob_name
        )
        
        download_path.parent.mkdir(parents=True, exist_ok=True)
        with open(download_path, "wb") as download_file:
            download_file.write(blob_client.download_blob().readall())
        
        logger.info(f"Downloaded {container_name}/{blob_name} to {download_path}")
